openapi: 3.0.1
info:
  title: Bot API
  version: 1.0.0
paths:
  /tg-chat/{id}:
    post:
      x-additional-comment: Метод для регистрации чата
      summary: Зарегистрировать чат
      description: |
        Регистрирует новый Telegram-чат в системе для получения уведомлений.
        Чат идентифицируется уникальным ID, который должен совпадать с реальным Telegram Chat ID.

      parameters:
        - name: id
          in: path
          required: true
          description: |
            Уникальный идентификатор Telegram-чата в формате int64.
            Должен соответствовать реальному `chat.id` из Telegram API.
          schema:
            type: integer
            format: int64
            example: -1002056789012
      responses:
        '200':
          description: |
            Чат успешно зарегистрирован. Система начала отслеживание ссылок для этого чата.
        '400':
          description: |
            Некорректный запрос. Возможные причины:
            - ID чата не соответствует формату int64
            - Чат с таким ID уже зарегистрирован
    delete:
      x-additional-comment: Метод для удаления чата
      summary: Удалить чат
      description: |
        Полностью удаляет чат из системы, включая все связанные отслеживаемые ссылки и настройки.
        После удаления чат перестает получать уведомления.

      parameters:
        - name: id
          in: path
          required: true
          description: |
            Идентификатор зарегистрированного Telegram-чата.
            Должен существовать в системе.
          schema:
            type: integer
            format: int64
            example: -1002056789012
      responses:
        '200':
          description: |
            Чат и все связанные данные успешно удалены.
            Тело ответа отсутствует.
        '400':
          description: |
            Некорректный запрос. Возможные причины:
            - Неверный формат ID чата
            - ID не соответствует числовому формату int64
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
        '404':
          description: |
            Чат не найден в системе. Возможные причины:
            - Чат никогда не регистрировался
            - Чат уже был удален ранее
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
  /links:
    get:
      x-additional-comment: Метод для получения отслеживаемых ссылки
      summary: Получить все отслеживаемые ссылки
      description: |
        Возвращает список всех ссылок, отслеживаемых для указанного чата.
        Включает метаданные: теги, фильтры и идентификаторы ссылок.

        **Особенности:**
        - Данные возвращаются пагинированно (поле `size` в ответе)
        - Пустой список означает отсутствие зарегистрированных ссылок

      parameters:
        - name: Tg-Chat-Id
          in: header
          required: true
          description: |
            Идентификатор чата, для которого запрашиваются ссылки.
            Должен соответствовать зарегистрированному чату.
          schema:
            type: integer
            format: int64
            example: -1002056789012
      responses:
        '200':
          description: |
            Успешный ответ содержит:
            - Массив объектов `LinkResponse`
            - Общее количество ссылок в поле `size`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListLinksResponse'
              example:
                links:
                  - id: 123
                    url: "https://github.com/user/repo"
                    tags: [ "backend", "monitoring" ]
                    filters: [ "new_commits" ]
                  - id: 456
                    url: "https://stackoverflow.com/questions"
                    tags: [ "support" ]
                    filters: [ "new_answers" ]
                size: 2
        '400':
          description: |
            Некорректный запрос. Возможные причины:
            - Неверный формат Tg-Chat-Id
            - Чат не зарегистрирован в системе
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
    post:
      x-additional-comment: Метод для отслеживания ссылки
      summary: Добавить отслеживание ссылки
      description: |
        Регистрирует новую ссылку для отслеживания в указанном чате.
        Поддерживает настройку фильтров и тегов для гибкой настройки уведомлений.

        **Требования к ссылке:**
        - Должна быть валидным URL
        - Не должна дублировать существующие ссылки в этом чате

      parameters:
        - name: Tg-Chat-Id
          in: header
          required: true
          description: |
            Идентификатор чата, к которому привязывается ссылка.
          schema:
            type: integer
            format: int64
            example: -1002056789012
      requestBody:
        description: |
          Конфигурация отслеживаемой ссылки.
          Поле `link` обязательно, `tags` и `filters` опциональны.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddLinkRequest'
            example:
              link: "https://github.com/opensource/project"
              tags: [ "development", "urgent" ]
              filters: [ "new_releases", "hotfixes" ]
        required: true
      responses:
        '200':
          description: |
            Ссылка успешно добавлена. Возвращает созданный ресурс с:
            - Автоматически сгенерированным ID
            - Нормализованным URL
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LinkResponse'
              example:
                id: 789
                url: "https://github.com/opensource/project"
                tags: [ "development", "urgent" ]
                filters: [ "new_releases", "hotfixes" ]
        '400':
          description: |
            Ошибка обработки запроса. Возможные причины:
            - Невалидный URL
            - Пустое тело запроса
            - Неподдерживаемый фильтр/тег
            - Ссылка уже отслеживается в этом чате
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
    delete:
      x-additional-comment: Метод для удаления отслеживания ссылки
      summary: Убрать отслеживание ссылки
      description: |
        Прекращает отслеживание указанной ссылки для заданного чата.
        Удаляет связь между чатом и ссылкой, но не удаляет саму ссылку из системы (если она используется другими чатами).

        **Важно:**
        - Для идентификации используется комбинация Tg-Chat-Id и Link-Url
        - После удаления чат перестает получать уведомления по этой ссылке

      parameters:
        - name: Tg-Chat-Id
          in: header
          required: true
          description: |
            Идентификатор чата, из которого нужно удалить ссылку.
            Должен быть зарегистрирован в системе.
          schema:
            type: integer
            format: int64
            example: -1002056789012
        - name: Link-Url
          in: header
          required: true
          description: |
            URL отслеживаемой ссылки в кодированном виде (RFC 3986).
            Должен точно совпадать с сохраненным значением (регистр, слэши и т.д.).
          schema:
            type: string
            format: uri
            example: "https://github.com/user/repo/pulls"
      responses:
        '200':
          description: |
            Ссылка успешно удалена из отслеживаемых для указанного чата.
            Возвращает полные данные удаленной связи.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LinkResponse'
              example:
                id: 123
                url: "https://github.com/user/repo/pulls"
                tags: [ "backend" ]
                filters: [ "new_pulls" ]
        '400':
          description: |
            Некорректный запрос. Возможные причины:
            - Невалидный формат Tg-Chat-Id
            - URL содержит синтаксические ошибки
            - Отсутствует обязательный заголовок
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
        '404':
          description: |
            Связь не найдена. Возможные причины:
            - Указанный чат не отслеживает данную ссылку
            - Ссылка или чат не существуют в системе
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
  /stats/{chatId}:
    get:
      x-additional-comment: Метод для получения статистики чата
      summary: Получить статистику чата
      description: |
        Возвращает текстовую статистику по отслеживаемым ссылкам в формате:
        "Ссылок: X, Обновлений за 24ч: Y, Активных фильтров: Z"

        **Формат ответа:** plain text

      parameters:
        - name: chatId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Текстовая статистика
          content:
            text/plain:
              schema:
                type: string
                example: "Ссылок: 5, Обновлений за 24ч: 12, Активных фильтров: 3"
        '404':
          description: Чат не найден
  /tracking/preferences:
    put:
      x-additional-comment: Метод для настроек отслеживания
      summary: Заменить настройки отслеживания
      description: |
        Полностью заменяет текущие настройки отслеживания для пользователя.
        Принимает данные в формате `application/x-www-form-urlencoded`.

        **Сброс настроек:**
        - Если параметры не переданы, восстанавливаются настройки по умолчанию

      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                interval:
                  type: integer
                  description: Интервал проверки в минутах
                notifyEmail:
                  type: boolean
                  description: Разрешить email-уведомления
                priority:
                  type: string
                  enum: [ low, medium, high ]
            example:
              interval: 30
              notifyEmail: true
              priority: high
      responses:
        '200':
          description: Настройки успешно применены
          content:
            text/plain:
              schema:
                type: string
                example: "Preferences updated"
        '422':
          description: Неверные значения параметров
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
  /chats/rename:
    put:
      x-additional-comment: Метод изменения имени чата
      summary: Изменить отображаемое имя чата
      description: |
        Обновляет псевдоним чата в системе. Не влияет на идентификатор.

        **Сценарий использования:**  
        Пользователь хочет дать понятное имя групповому чату вместо ID

      parameters:
        - name: Tg-Chat-Id
          in: header
          required: true
          schema:
            type: integer
            format: int64
        - name: New-Name
          in: header
          required: true
          schema:
            type: string
            maxLength: 50
            example: "Команда бэкенда"
      responses:
        '200':
          description: Имя успешно обновлено
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatInfo'
        '400':
          description: |
            Ошибка валидации:
            - Слишком длинное имя (>50 символов)
            - Неподдерживаемые символы
  /links/check:
    get:
      x-additional-comment: Метод для проверки отслеживания ссылки
      summary: Проверить отслеживание ссылки
      description: |
        Проверяет, отслеживается ли конкретная ссылка в чате.
        Возвращает простой ответ true/false.

        **Сценарий использования:**  
        Пользователь хочет убедиться, что ссылка уже добавлена перед повторной попыткой

      parameters:
        - name: Tg-Chat-Id
          in: header
          required: true
          schema:
            type: integer
            format: int64
        - name: Link-Url
          in: header
          required: true
          schema:
            type: string
            format: uri
      responses:
        '200':
          description: Результат проверки
          content:
            application/json:
              schema:
                type: boolean
                example: true
        '400':
          description: Невалидные параметры
  /notifications:
    patch:
      x-additional-comment: Метод для переключения режима уведомлений
      summary: Переключить режим уведомлений
      description: |
        Включает или отключает все уведомления для чата через заголовки.
        Не требует тела запроса. Простой переключатель состояния.

        **Сценарий использования:**  
        Пользователь хочет временно отключить уведомления во время отпуска

      parameters:
        - name: Tg-Chat-Id
          in: header
          required: true
          schema:
            type: integer
            format: int64
        - name: Notifications-Enabled
          in: header
          required: true
          schema:
            type: boolean
            example: false
      responses:
        '200':
          description: |
            Состояние успешно изменено. Возвращает новое состояние.
          content:
            text/plain:
              schema:
                type: string
                example: "Уведомления отключены"
        '400':
          description: Неверный формат заголовков
  /filters/{linkId}:
    put:
      x-additional-comment: Метод для обновления фильтров ссылок
      summary: Обновить фильтры ссылки
      description: |
        Обновляет фильтры для отслеживаемой ссылки,
        позволяет частично изменять конфигурацию без передачи всего объекта.

        **Особенности:**
        - Поддерживает добавление/удаление отдельных фильтров

      parameters:
        - name: linkId
          in: path
          required: true
          description: ID ссылки из системы
          schema:
            type: integer
            format: int64
            example: 123
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateFiltersRequest'
            example:
              filters: [ "new_commits", "hotfixes" ] # Удаляет второй фильтр
        required: true
      responses:
        '200':
          description: Фильтры успешно обновлены
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LinkResponse'
        '403':
          description: Доступ запрещен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
components:
  schemas:
    ChatInfo:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: -1002056789012
        displayName:
          type: string
          nullable: true
          example: "Команда бэкенда"
        trackingEnabled:
          type: boolean
          example: true
        linksCount:
          type: integer
          example: 5
    LinkResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        url:
          type: string
          format: uri
        tags:
          type: array
          items:
            type: string
        filters:
          type: array
          items:
            type: string
    ApiErrorResponse:
      type: object
      properties:
        description:
          type: string
        code:
          type: string
        exceptionName:
          type: string
        exceptionMessage:
          type: string
        stacktrace:
          type: array
          items:
            type: string
    AddLinkRequest:
      type: object
      properties:
        link:
          type: string
          format: uri
        tags:
          type: array
          items:
            type: string
        filters:
          type: array
          items:
            type: string
    ListLinksResponse:
      type: object
      properties:
        links:
          type: array
          items:
            $ref: '#/components/schemas/LinkResponse'
        size:
          type: integer
          format: int32
    UpdateFiltersRequest:
      type: object
      properties:
        filters:
          type: array
          items:
            type: string
          description: |
            Новый массив фильтров.
          example: [ "new_commits", "releases" ]